### ISSUE TITLE
Per-Game Launch Parameters

### ISSUE THREAD

**Issue by RyzaJr** [dh4/mupen64plus-qt#11]
Any chance of having each game launch with specific parameters?

I mainly would like this in order to launch different controller input settings or cheats and whatnot per game.

Thanks.

**Comment by dh4** [comment]
I've toyed around with the idea of having per-game settings but always backed off since it would be a decent amount of work.

I think having a simple per-game parameters option would be fairly easy to implement though and I could see how it could be quite useful. I'm quite busy lately but look for this when I have some time to work on it.

**Comment by RyzaJr** [comment]
Thanks, I appreciate it.

Mupen64Plus Qt is, in my opinion, so close to being perfectly functional yet light weight. The only function it is missing is per-game parameters.

**Comment by dh4** [comment]
Thank you. It's nice to hear that people find this useful.

I had a little time to work on it today and added this feature. You can download the development build listed in the README to test it out. Check it out and let me know what you think or any issues you find with it. You can access it under Settings->Configure Game. It allows you to specify custom plugins, a config directory and parameters for each game.

**Comment by RyzaJr** [comment]
Seems to work just fine! 

I had to figure out how to get it to read different input config files, which was just setting the controller config mode to 0 so it's not overwritten then saving that mupen64plus.cfg to it's on separate directory directory for that game, but it works!

I only wish Mupen64Plus could read different .cfg files instead of having to read different directories, but that's another issue.
