### ISSUE TITLE
Choice of the folders and refresh list

### ISSUE THREAD

**Issue by Marc34** [dh4/mupen64plus-qt#12]
Hi

It seems not possible to choose a folder with his sub-folders or to choose several folders at a time. And "Refresh list" doesn't scan sub-folders. That could be very useful.

**Comment by dh4** [comment]
I'll add a recursive scan when I have some time. I could see this being useful. How many levels deep would you like it to scan? I'll probably cap it at one level since I think that will cover most use cases or let the user choose.

**Comment by Marc34** [comment]
One level seems good.
