### ISSUE TITLE
qmake can't detect quazip outside of debian

### ISSUE THREAD

**Issue by sl1pkn07** [dh4/mupen64plus-qt#13]
qmake can't detect quazip because the .pro script is a ubuntu/debian centric

**Comment by sl1pkn07** [comment]
ok. now know what happen

i have installed dkpkg on my archlinux for get the installation/upgrade/uninstall scripts from deb packages. then if launch the dpkg like in the qmake script

```
if $(dpkg -l | grep libquazip5-dev | grep ^ii > /dev/null); then echo OK; else echo NOK; fi
NOK
```

archlinux also uses -libquazip5 like a debian/ubuntu(?)

**Comment by dh4** [comment]
Should default to linking libquazip5 now instead of libquazip-qt5 if neither are installed by dpkg. This is probably the better way to handle it.
