### ISSUE TITLE
[feature request]User friendly controller configuration

### ISSUE THREAD

**Issue by AlessandroPorcelli91** [dh4/mupen64plus-qt#15]
Hello there, very nice GUI for mupen64plus! Have you thought about adding a controller configuration which would allow the user to bind the buttons simply by pressing them? It's not necessary at all but I think it would help less experienced users migrating from PJ64. I am no coder, so I don't actually know how much of an hassle that would be to implement.

keep it up!

Alessandro

**Comment by dh4** [comment]
While I agree a graphical interface for configuring controller configuration would be user friendly, I have no plans of adding it currently. It would require me to bring in SDL as a dependency and also do some hackish manipulation on the mupen64plus.cfg file (which I want to stay away from) since this is a launcher and not a full-fledged frontend.

Perhaps if I were to convert this to use the Mupen64Plus API or the console UI adds some sort of a helper for configuring input, but my efforts are more focused on CEN64-Qt, and adding this would be a decent amount of work that only benefits Mupen64Plus-Qt.

**Comment by AlessandroPorcelli91** [comment]
Of course, there would be no haste in doing that (no pun intended, kinda :P) I have also installed CEN64-Qt though that's way too slow on my low end machine. I wish I had some useful knowledge to help with this, perhaps someday it will be so and I'd be glad and honored to contribute to your projects. Have a nice day man!

Alessandro

**Comment by es20490446e** [comment]
I suggest instead [changing the default automatic configuration](https://github.com/dh4/mupen64plus-qt/issues/16). If we see that's not enough, then we can implement an interface.

**Comment by AlessandroPorcelli91** [comment]
@es20490446e Oh, that's not an issue for me personally, I have enough experience with the emulator to mess around with any configuration I need. I just remember having had major troubles some years ago, migrating from PJ64 which comes with a user frendly interface. I see people migrating to Linux running PJ64 through WINE rather than playing on mupen64plus because that's just too much for them to do, and that's a shame.

**Comment by Vlad-Romanov** [comment]
I know this is old, but m64py has a controller configurator if I am not mistaken. Maybe part of it can be forked & added into this launcher?

**Comment by es20490446e** [comment]
Since it uses a different programming language, it cannot be forked. Only rewritten.

**Comment by dh4** [comment]
@es20490446e is correct. m64py is written in python instead of C++. Some of the logic could potentially be re-used, but it would have to be completely re-written.

I'd like to see controller configuration in this eventually (as well as it using the API instead of the console frontend), as I think it's the last thing keeping this from being user-friendly. I lack the time and motivation to dedicate to it currently though.

**Comment by robalni** [comment]
I'm actually working on turning this launcher into a real frontend using the API and I just started working on the controller configuration. Just wanted to let you know that so we don't do double work. My plan is for it to become the official UI of Mupen64Plus.

**Comment by dh4** [comment]
Great! Keep me updated. I was hoping someone would take the initiative and turn this into a frontend since I haven't had much time to work on it the last few years.

**Comment by Vlad-Romanov** [comment]
Great to hear, this front-end is of much potential :)
controller configurator would be icing on the cake! 
I think there is another front-end for mupen64plus that also has controller config, can't remember the name...

**Comment by wmcmurray** [comment]
For those stumbling upon this, I've found this online tool : http://html5gamepad.com/ that lets you see which buttons are pressed on your USB controller ! Very useful when setting bindings manually :slightly_smiling_face:

**Comment by robalni** [comment]
I have been working with making this a real frontend for a while now. Maybe I should have written this earlier but the input config is sort of done (maybe there could be some sliders for e.g. deadzone) and the rest of it is almost finished, it's just cheats and some other things that are missing and it probably has some bugs. You can find it here:

https://github.com/robalni/mupen64plus-ui

**Comment by es20490446e** [comment]
Thank you. And merging both repositories?

**Comment by dh4** [comment]
@robalni I just built and tested it on my machine. Looks awesome and it works great! Thanks for working on converting this into a full frontend! It's something I always wanted to do eventually but haven't had the time lately.

Minor issue: It throws the error "[ui] info: Go to settings and select an input plugin first" when trying to open the controller config dialog until you open the main settings and click OK to save them for the first time.

@es20490446e Yes we can probably merge the repositories together at some point when it's ready so the code isn't maintained in two places. We might see if the mupen64plus team will give us a repo under their organization (https://github.com/mupen64plus).

**Comment by dh4** [comment]
Closing this as the latest commits add a GUI for controller configuration.

**Comment by es20490446e** [comment]
🥳
