### ISSUE TITLE
Gamepads are comfortable

### ISSUE THREAD

**Issue by es20490446e** [dh4/mupen64plus-qt#16]
As reported in [Launchpad](https://bugs.launchpad.net/ubuntu/+source/mupen64plus-input-sdl/+bug/1624463):

Using a generic PlayStation like game pad [Logitech Dual Action 2](http://www.kustompcs.co.uk/acatalog/4707.jpg), the automatic configuration has major usability drawbacks:

- The analog range is too short, making movement hard. In Super Smash Bros, characters don't jump diagonally.

- C-buttons, instead of isolated as in the original console game pad, are placed in the second analog. This makes pressing buttons by accident a frequent issue. In Golden Eye camera movement prevents the game from been playable, where in Road Rash you frequently discard weapons permanently.

- Z-trigger and Left-trigger are placed both in the left triggers of the game pad. But you usually need to press both simultaneously, where that placement only allows pressing one button at a time.

The solution is this:

- Ignore the console's native analog range, and choose a wider one.
- Place C-buttons in the game pad triggers.
- Place the Z-trigger in the regular button's side, where pressing the rest is usable.

After testing thoroughly various configurations with multiple games, the following seems to be the one that responds better in any circumstance:

```
# The minimum absolute value of the SDL analog joystick axis to move the N64 controller axis value from 0. For X, Y axes.
AnalogDeadzone = "338,338"
# An absolute value of the SDL joystick axis >= AnalogPeak will saturate the N64 controller axis value (at 80). For X, Y axes. For each axis, this must be greater than the corresponding AnalogDeadzone value
AnalogPeak = "21200,21200"
# Digital button configuration mappings
DPad R = "axis(4+) hat(0 Right)"
DPad L = "axis(4-) hat(0 Left)"
DPad D = "axis(5+) hat(0 Down)"
DPad U = "axis(5-) hat(0 Up)"
Start = "button(9)"
Z Trig = "button(2)"
B Button = "button(0)"
A Button = "button(1)"
C Button R = "button(5)"
C Button L = "button(4)"
C Button D = "button(7)"
C Button U = "button(6)"
R Trig = "button(3)"
L Trig = "button(8)"
Mempak switch = ""
Rumblepak switch = ""
# Analog axis configuration mappings
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"
```

**Comment by AlessandroPorcelli91** [comment]
Had to do a similar thing for the Mayflash Gamecube Controller Adapter.

**Comment by es20490446e** [comment]
Well, the point is this game-pad is the most generic one that exist. So if that works most game-pads will do, which is a good place to start with.

**Comment by dh4** [comment]
This is not something I have any control over. Please report this upstream:
https://github.com/mupen64plus

**Comment by es20490446e** [comment]
I've just reported it to [Mupen](https://github.com/mupen64plus/mupen64plus-core/issues/187). Thanks for your attention 😉
