### ISSUE TITLE
The layout is neat

### ISSUE THREAD

**Issue by es20490446e** [dh4/mupen64plus-qt#17]
The only thing that the game layout needs is the grid view, with extra large images, the game title as label, and game information downloaded as default (https://goo.gl/yPdhsI)

The rest of the layout settings don't deliver any added value, and I would remove them.

**Comment by dh4** [comment]
While I agree that the grid view is the most aesthetic, your assertion that the other views don't add any value is simply incorrect. Other users will have different use cases and preferences.
