### ISSUE TITLE
Default resolution is of high quality

### ISSUE THREAD

**Issue by es20490446e** [dh4/mupen64plus-qt#19]
Currently the default resolution is set to be the native of the console. I would suggest that instead it's the greatest that the screen supports that has a 4:3 aspect ratio.

**Comment by dh4** [comment]
This is an upstream issue as well. "Default" just means provide no resolution option to mupen64plus, so it uses it's default resolution.

**Comment by es20490446e** [comment]
Reported [here](https://github.com/mupen64plus/mupen64plus-core/issues/188). Thanks!
