### ISSUE TITLE
[request] Qt5 port

### ISSUE THREAD

**Issue by ahjolinna** [dh4/mupen64plus-qt#2]
Like the title suggest, is there a Qt5 port coming? if yes when?

**Comment by sergiobenrocha2** [comment]
You only need to change line 61 of *.pro to:

LIBS += -lquazip-qt5

Or it'll link against the libquazip for Qt4.

**Comment by sergiobenrocha2** [comment]
Btw, what's this black window when you refresh list?

![mupen64plus-qt](https://cloud.githubusercontent.com/assets/5431285/7905797/90df1582-07f5-11e5-9d08-0d023cdbe2ef.png)

It was not showing with Qt4

**Comment by dh4** [comment]
Check the commit I just pushed. Should fix that black window. Thanks for pointing that out.

I've also added a section in the README about building with Qt5.
