### ISSUE TITLE
Default settings are the optimal for most cases

### ISSUE THREAD

**Issue by es20490446e** [dh4/mupen64plus-qt#20]
I would make these the default:

- "On screen display" on, as people cannot figure out what keyboard shortcuts do if there isn't any message on the screen. In fact I think this option should be hidden, as there's no situation where disabling it would be desirable.

- "Fullscreen" on, as this is how nearly all people is expecting to play. Disabling the option would be useful only for very specific cases, or for debugging.

- "Vertical Sync" on, as that would have no performance penalty in most computers these days while making the playing more comfortable to the eye.

**Comment by dh4** [comment]
I've modified the OSD option to match upstream's default (on). 

Using a multi-screen setup, I can definitely say that a default fullscreen is not desirable. I'll be leaving that as windowed to match upstream. Report vertical sync upstream if you think the default should be changed.

**Comment by es20490446e** [comment]
Reported [here](https://github.com/mupen64plus/mupen64plus-core/issues/189). Thank you.
