### ISSUE TITLE
Windowed resolution looks good in any screen size

### ISSUE THREAD

**Issue by es20490446e** [dh4/mupen64plus-qt#21]
I would make the emulator decide the windowed screen resolution based on the resolution of the desktop.

**Comment by dh4** [comment]
An upstream issue. Yes, I could determine a user's screen size and try to choose the best resolution for them, but it's not a business I want to get into. Just choose the resolution once that best fits your monitor and forget about it.

**Comment by es20490446e** [comment]
[Upstreamed!](https://github.com/mupen64plus/mupen64plus-core/issues/190)
