### ISSUE TITLE
Cheats are accesible

### ISSUE THREAD

**Issue by es20490446e** [dh4/mupen64plus-qt#23]
Cheats sometimes deliver relevant functionalities to the games, as the ability to unlock all the characters and scenarios. I would provide an obvious mean to enable them. Thanks!

**Comment by dh4** [comment]
You can use the additional parameters option to specify cheats (either globally under "Configure..." or by game in the "Configure Game..." settings dialog):
https://github.com/dh4/mupen64plus-qt#additional-parameters-cheat-support

I don't plan on providing a more hands-on graphical interface for this.
