### ISSUE TITLE
Localisation issue in game settings

### ISSUE THREAD

**Issue by mazes-80** [dh4/mupen64plus-qt#26]
First great job, my son began to play N64 some weeks ago, but whenever he was trying to seek for a game, he had to randomly select until he finds the one as he not grown enough to read.
The grid view with image, was exactly what he needed. Moreover as it's just a launcher, he can't be as tempted to mess up all settings as with a front-end. 

However I regret there's no install option in the makefile
Also I noticed failure when I tried to set game to use a non default plug-in. After taking a look at the generated command line, I noticed that it tried to launch unavailable plug-in:
/usr/bin/mupen64plus --nosaveoptions --datadir HOME/.config/mupen64plus-qt --configdir HOME/.config/mupen64plus --plugindir /usr/lib64/mupen64plus/ --emumode 2 --osd --windowed --resolution 1024x768 --gfx mupen64plus-video-glide64mk2 --audio Défaut --input Défaut --rsp Défaut /tmp/mupen64plus-qt/temp.n64

Was then trivial to understand that default was translated to my user language when generating command line.

**Comment by mazes-80** [comment]
diff --git a/src/dialogs/gamesettingsdialog.cpp b/src/dialogs/gamesettingsdialog.cpp
index b1dca12..cee5dd5 100644
--- a/src/dialogs/gamesettingsdialog.cpp
+++ b/src/dialogs/gamesettingsdialog.cpp
@@ -112,22 +112,22 @@ void GameSettingsDialog::browseConfig()
 
 void GameSettingsDialog::editGameSettings()
 {
-    if (ui->videoBox->currentText() != "default")
+    if (ui->videoBox->currentText() != tr("default"))
         SETTINGS.setValue(fileName+"/video", ui->videoBox->currentText());
     else
         SETTINGS.setValue(fileName+"/video", "");
 
-    if (ui->audioBox->currentText() != "default")
+    if (ui->audioBox->currentText() != tr("default"))
         SETTINGS.setValue(fileName+"/audio", ui->audioBox->currentText());
     else
         SETTINGS.setValue(fileName+"/audio", "");
 
-    if (ui->inputBox->currentText() != "default")
+    if (ui->inputBox->currentText() != tr("default"))
         SETTINGS.setValue(fileName+"/input", ui->inputBox->currentText());
     else
         SETTINGS.setValue(fileName+"/input", "");
 
-    if (ui->rspBox->currentText() != "default")
+    if (ui->rspBox->currentText() != tr("default"))
         SETTINGS.setValue(fileName+"/rsp", ui->rspBox->currentText());
     else
         SETTINGS.setValue(fileName+"/rsp", "");

**Comment by mazes-80** [comment]
Here's a patch to fix this issue
[mupen64plus-qt-settings-translate.patch.txt](https://github.com/dh4/mupen64plus-qt/files/554434/mupen64plus-qt-settings-translate.patch.txt)

May be a pull request would be more appropriate

**Comment by mazes-80** [comment]
Just noticed another issue with temporary rom path for multiple user.
see: src/emulation/emulatorhandler.cpp -> startEmulator()
QString tempDir = QDir::tempPath() + "/"+AppNameLower;
changing to:
QString tempDir = QDir::tempPath() + "/"+qgetenv("USER")+"-"+AppNameLower;
would fix this issue to.

Sorry to speak about multiple issue in a single bug report.
Let me know if you prefer opening per issue thread (that's the way it should be, but ...)

**Comment by dh4** [comment]
Thanks for pointing out these issues. I've fixed both of them with the latest commits. There may be other small issues with when using the French translation, though hopefully that's the only one. I don't test often with the translation. Let me know if you find any others.

If you want, there's a few missing words and phrases needing to be translated to French. I don't speak it myself, so haven't been able to complete it.
