### ISSUE TITLE
Allow for Configuring TheGamesDB Request Timeout

### ISSUE THREAD

**Issue by xd1936** [dh4/mupen64plus-qt#27]
Requests like [this one](http://thegamesdb.net/api/GetGame.php?name=Super%20Mario%2064&platform=Nintendo%2064) to thegamesdb.net can take 10-45 seconds, and mupen64plus-qt tends to time out when scraping. Please allow us to increase the time that mupen64plus-qt waits before giving up on the request!

**Comment by dh4** [comment]
I've added the ability to specify a custom timeout within the configuration file. See the changes to the README for instructions.
