### ISSUE TITLE
Borderless window mode

### ISSUE THREAD

**Issue by Beanow** [dh4/mupen64plus-qt#30]
This type of fullscreen mode would be much appreciated if possible. Since I have the controller(s) set up for the games. It would be great if we could tab out without screen flickers and interrupting gameplay.

**Comment by dh4** [comment]
Could you explain more what you are looking for that View->Full Screen does not provide? It should already be a borderless window mode. It just hides the menu and scrollbars and then calls QWidget::showFullScreen() (https://doc.qt.io/qt-5/qwidget.html#showFullScreen). 

Or are you talking about the mupen64plus emulation window? I don't have any control over that beyond sending --window or --fullscreen to it along with a resolution.

**Comment by Beanow** [comment]
Yeah, I see the `View > Full-screen` works nicely and is borderless windowed. I did mean the emulation window. Which in `Settings > Configure > Graphics > Fullscreen` claims a display for itself causing flickers and such.

**Comment by dh4** [comment]
Yeah there's nothing I can do for that since that's handled by mupen64plus (https://github.com/mupen64plus) rather than the launcher. 

What I've done to handle the same situation on my machine is add a custom rule to my window manager to launch mupen64plus without a border. I'm using Linux though. Not sure if there's a similiar option if you're using Windows or MacOS.

**Comment by Beanow** [comment]
That's a great suggestion actually. I had never used those rules before. But Kwin also has them and didn't take long to work out something better than the normal fullscreen setting. Still requires focus to have the controllers work, but it's better than flickers and screen resolutions changing and the game minimizing.

**Comment by dh4** [comment]
Nice. Glad you were able to find a setting that worked.
