### ISSUE TITLE
Thumbnail not updating

### ISSUE THREAD

**Issue by nIQnutn** [dh4/mupen64plus-qt#31]
Updating thumbnail was not possible with "Ocarina of Time - Master Quest". First, It was detected as another game and I had a different thumbnail. When I updated with the correct name, the thumbnail was still the same. 
Looking in ~/.local/share/mupen64plus-qt/cache there was 2x thumbnails. The first was .jpg file, the one I saw and the second was a .png file ( Ocarina of Time - Master Quest). Deleting the .jpg file fix the issue. 
I'm using Debian Stretch v1.9.

**Comment by dh4** [comment]
I'll create a fix for this when I get a chance. It just needs to delete the old image when it downloads another one. Thanks for reporting.

**Comment by dh4** [comment]
Latest commit should fix this issue.
