### ISSUE TITLE
Failed to build for Debian Stretch i386

### ISSUE THREAD

**Issue by karl6994** [dh4/mupen64plus-qt#32]
I use this with Fedora without problems, but won't work for Debian Stretch stable i386
Any ideas what I'm doing wrong? Perhaps I'm missing something?

debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc -i -b failed
mv: cannot stat '../mupen64plus-qt_1.10*.deb': No such file or directory

**Comment by dh4** [comment]
Is there any more verbose output from debuild? I'm assuming this is something to do with the architecture since I've only tested the build scripts on x86_64, but it's hard to tell without a more specific error message.

**Comment by karl6994** [comment]
Disregard, I was missing a dependency, somehow missed one of them. Apologies!!
