### ISSUE TITLE
Void Linux compatibility

### ISSUE THREAD

**Issue by Jakecheslekov** [dh4/mupen64plus-qt#34]
Hey dude, any idea how I can get this to compile in Void Linux? m64py doesn't seem to work... ever.

**Comment by dh4** [comment]
There are instructions here for building on Linux:
https://github.com/dh4/mupen64plus-qt#building-linux

You just need to translate the package list there into the names of the comparable packages to install on Void Linux. Post a build log of the output of qmake and make if you're having a specific issue after getting the needed packages installed.
