### ISSUE TITLE
Downloading game info fails

### ISSUE THREAD

**Issue by cromerc** [dh4/mupen64plus-qt#35]
thegamesdb.net api has changed, this causes the info download to fail.

This is the new api: https://api.thegamesdb.net/

Apparently it requires an apikey which I assume would would be needed from the people that run thegamesdb.net.

**Comment by cromerc** [comment]
Found some info on how to request an api key:
http://wiki.thegamesdb.net/index.php/API_Introduction

**Comment by dh4** [comment]
The latest commit should get it working again for the time being using their legacy site. See here for downloads of the latest commit:
https://github.com/dh4/mupen64plus-qt#development-builds

I've put in a request for an API key from them and will work on implementing their new API once I receive that.

**Comment by dh4** [comment]
The commit here implements version 2 of their API: https://github.com/dh4/mupen64plus-qt/commit/ffec5ce9c2163c41330194b62f4b5dcf3d8a3a42

I will be releasing version 1.12 soon to incorporate the change since the older versions can no longer download information and images from their API.
