### ISSUE TITLE
Have you considered building a Flatpak or Snap?

### ISSUE THREAD

**Issue by 1h8me2** [dh4/mupen64plus-qt#37]
Not sure if this would reduce your need for upkeep and troubleshooting different build scripts for distros. There does not seem to be any current mupen64plus build in the Snap store or Flathub. You may be able to use a lot of the work that was done for the Dolphin-emu Flatpak as that also uses QT5. https://github.com/flathub/org.DolphinEmu.dolphin-emu

**Comment by dh4** [comment]
This is something that would be nice to have but not a priority for me. I've never built a Flatpak or Snap so it would take some time for me to get up to speed on them. Plus I would have to create one for mupen64plus as well (or bundle it in) to make it useful.

If this is something you'd be interested in doing I'd be glad to provide assistance.

**Comment by dh4** [comment]
Closing old issue.
