### ISSUE TITLE
Feature Request - Configuration Options

### ISSUE THREAD

**Issue by inukaze** [dh4/mupen64plus-qt#38]
Hi there. i just want to request a user friendly configuration for 

Controller Inputs [4 Controls]

Video Configuration : Because plugins like Glide64, Glide64Mk2, Rice, have a lot of options. but its should be manually configure in the mupen64plus.cfg file.

That its all mainly

**Comment by dh4** [comment]
Check out the frontend version of this by @robalni
https://github.com/robalni/mupen64plus-ui

It's not in a release state yet but has controller configuration. It's much easier to build it if you have the mupen64plus beta 2.5.9 installed.

**Comment by inukaze** [comment]
Uncompilable : 

```
src/common.cpp: In function ‘void byteswap(QByteArray&)’:
src/common.cpp:96:41: error: ‘assert’ was not declared in this scope
         assert(romData.length() % 8 == 0);
                                         ^
Makefile:782: fallo en las instrucciones para el objetivo 'common.o'
make: *** [common.o] Error 1

```

**Comment by dh4** [comment]
It compiles fine for me assuming I have mupen64plus 2.5.9 installed. 

How are you trying to compile it? What OS are you using? assert.h is a part of the standard C library, so that shouldn't be missing on your system.

**Comment by inukaze** [comment]
@dh4 : Thanks for the information that GUI works wonderfull, i make a feature request in that project. well the developer(s) fix some files and after updates i download newer version and i can compile it without problems. 

i make part of my script for Download, Configure, Compile and install -> [mupen64plus-git](https://github.com/inukaze/maestro/blob/master/Videojuegos/Guion/Descargar-Compilar-Instalar/mupen64plus-git) but i need improve to default install <<all>> but the final user can use by this way for example

```
./mupen64plus-git ui #Install mupen64plus-ui
./mupen64plus-git qt #Install mupen64plus-qt
./mupen64plus-git pỳ #Install M64Py
./mupen64plus-git rsp-hle
```

well i am thinking how not write too much xD and how i should use "case" for the optimal version i can write

**Comment by dh4** [comment]
Closing this as the latest commits add a GUI for controller input
