### ISSUE TITLE
No cover for Ocarina of Time

### ISSUE THREAD

**Issue by sergiobenrocha2** [dh4/mupen64plus-qt#4]
There is no cover for Legend of Zelda, The - Ocarina of Time (USA) (Rev B). I tried already to update it in  the File option. I can find the picture in ~/local/share/mupen64plus-qt/

![mupen64plus-qt](https://cloud.githubusercontent.com/assets/5431285/7385228/e9ba6e06-ee17-11e4-9d05-78f14274cd81.png)

**Comment by dh4** [comment]
Should be fixed. TheGamesDB changed the Ocarina of Time boxart from a JPG file to PNG. When I tested this the ~100 or so games I tested all had JPG artwork so I didn't bother to account for PNG images.

Could you compile the new commits and verify it works correctly now? You'll need to manually refresh the information for OoT or rename the image file extension.

Also fixed the issue with the label text overflowing onto the image seen in your screenshot.

**Comment by sergiobenrocha2** [comment]
Nice, it's working, thanks!
