### ISSUE TITLE
Hotkey configuration

### ISSUE THREAD

**Issue by TotalCaesar659** [dh4/mupen64plus-qt#42]
There are no hotkey configuration option, or even just the list of ones (only in mupen64plus.cfg, where they have difficult names like "key(100)", "key(97)" etc.). Is it possible to implement?

**Comment by dh4** [comment]
I don't have any plans to build a full GUI for editing hotkeys (something that could go in https://github.com/robalni/mupen64plus-ui though).

I could see a list of default hotkey configurations in a popup as useful though. And also a list of keycodes that could be referenced while using the mupen64plus.cfg editor could be useful.

Those can be found here BTW:
http://www.libsdl.org/release/SDL-1.2.15/include/SDL_keysym.h

**Comment by dh4** [comment]
I've added a pop up to the editor that lists all the key codes. I'll do something similar for the default controls (and put it in the Emulation menu probably).

**Comment by TotalCaesar659** [comment]
Thank you, it's much more comfortable, [updated](https://github.com/dh4/mupen64plus-qt/pull/43) Russian translation.

**Comment by dh4** [comment]
I've added a dialog in the help menu that lists the default key bindings for reference.

**Comment by TotalCaesar659** [comment]
Thanke, [updated](https://github.com/dh4/mupen64plus-qt/pull/44).
