### ISSUE TITLE
Q: How to delete the configuration file?

### ISSUE THREAD

**Issue by FrnandMG** [dh4/mupen64plus-qt#48]
I accidentally put the "documents" (where are all my files) as the roms path on config and causes the application to not work anymore.

I already tried uninstall and reinstall but the problem persists.

Some help with this. I'm using xubuntu 18.40 lts

thanks

**Comment by dh4** [comment]
You can edit the text configuration file at `~/.config/mupen64plus/mupen64plus-qt.conf`. Edit the 'roms' variable under [Paths] to remove your Documents folder.

Do you happen to know what type of file is causing it to crash? I'd like to find out what's causing the crash and fix it if possible.

**Comment by FrnandMG** [comment]
I edited the file and now it works perfectly. I have several types of files that could cause the problem maybe binary files (installers, etc). 

Thanks for the help. Keep up the great work. :-)
