### ISSUE TITLE
thegamesdb.net: api upgrade

### ISSUE THREAD

**Issue by mazes-80** [dh4/mupen64plus-qt#49]
the games db api should now be accessed with prefix v1, or v1.1 for supported options

[mupen64plus-qt-tgdb.patch.txt](https://github.com/dh4/mupen64plus-qt/files/4210959/mupen64plus-qt-tgdb.patch.txt)

**Comment by dh4** [comment]
Thanks for this. I've made the URLs customizable without recompiling as well since TheGamesDB doesn't seem to care about breaking things.
