### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by Aisyk** [dh4/mupen64plus-qt#5]
On Ubuntu 14.04 : 
error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory

Therefore, version of libquazip is installed : 0.6.2-0ubuntu1

**Comment by dh4** [comment]
You need libquazip1 to use the dynamically linked binary I've distributed. Ubuntu 14.10 and above have this. For 14.04, you'll need to follow the build instructions in the readme. It will automatically link to libquazip.so.0.

Let me know if you have any issues compiling it.
