### ISSUE TITLE
Core parameter "--saveoptions" is not an actual command line parameter for Mupen64Plus

### ISSUE THREAD

**Issue by Yersho** [dh4/mupen64plus-qt#51]
When running a rom with Mupen64Plus-Qt with the option "Save settings" turned on, it adds the parameter "--saveoptions" to the command line output. This can be seen in the logs with Mupen64Plus even giving an error message [UI-Console Warning: unrecognized command-line parameter '--saveoptions']. It does not seem to actually affect the ability for new plugin data to be written to the config file as when tested, new plugin configurations were properly loaded to the config file as if you simply ran Mupen64Plus from the command line or PowerShell. Unless Mupen64Plus-Qt is using this parameter for its own use I believe it should be removed and the setting "Save settings" should just simply remove the "--nosaveoptions" parameter from the command line operation when loading a game. I have included a text file of my log for reference.

Some additional information about my testing conditions:
I have built Mupen64Plus from source on March 23, 2020 and that was the build I was testing on. I am also using the latest release build of Mupen64Plus-Qt which I downloaded from here https://github.com/dh4/mupen64plus-qt/releases/tag/1.14. If this has already been addressed in Mupen64Plus-Qt in a source build then you can just close the issue right now.

Text file of log generated from Mupen64Plus-Qt: 
[Mupen64Plus-Qt Log.txt](https://github.com/dh4/mupen64plus-qt/files/4377895/Mupen64Plus-Qt.Log.txt)

**Comment by dh4** [comment]
Thanks for reporting this. Looks like --saveoptions was removed in Mupen64Plus 2.5 and I never noticed. The latest commit should fix the issue.
