### ISSUE TITLE
can't do sudo make install

### ISSUE THREAD

**Issue by Askmewho** [dh4/mupen64plus-qt#53]
hi, I compiled this frontend on aarch64 Linux on focal and I can't install it properly with sudo make install. maybe qmake didn't create the option to the makefile (install appears in the makefile but it doesn't work). I can execute it but can't open the config file that way. how to install it manually?? thanks!!

**Comment by dh4** [comment]
There is no `make install` for this. The resulting `mupen64plus-qt` binary in the root directory can be run from anywhere with `./mupen64plus-qt`. You could add it to somewhere in your PATH to launch it like a regular executable (like /usr/local/bin if that is in your PATH. There's also an example .desktop file and an icon that you can add to your system in the resources directory:
https://github.com/dh4/mupen64plus-qt/tree/master/resources

**Comment by dh4** [comment]
You could also review what the PKGBUILD for this in the AUR does to see how it's installed:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mupen64plus-qt

**Comment by Askmewho** [comment]
thanks for the explanation, closing. 👍
