### ISSUE TITLE
Unable to Save In-Game

### ISSUE THREAD

**Issue by Posiris** [dh4/mupen64plus-qt#54]
I'm on Ubuntu 20.10 and mupen64plus-qt 1.14-1.  I am unable to save in-game.  Games say that there is no mem pak detected.

**Comment by dh4** [comment]
This is a Mupen64Plus issue instead of the launcher. I would check your mupen64plus.cfg to make sure you haven't disabled the mempak under the controller settings. You can edit it in the launcher with Settings->Edit mupen64plus.cfg...

**Comment by Posiris** [comment]
*I have double checked the config file and "2" is set for mempak.  I 
will past the settings for controller 1 below.  Controllers 2-4 are set 
to "false" for plugged in. I had mapped the mempak switch as well to try 
and toggle it, and nothing happens at all.*

[Input-SDL-Control1]

# Mupen64Plus SDL Input Plugin config parameter version number. Please 
don't change this version number.

version = 2

# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL 
Device, 2=Fully automatic

mode = 2

# Specifies which joystick is bound to this controller: -1=No joystick, 
0 or more= SDL Joystick number

device = 0

# SDL joystick name (or Keyboard)

name = "Pro Controller"

# Specifies whether this controller is 'plugged in' to the simulated N64

plugged = True

# Specifies which type of expansion pak is in the controller: 1=None, 
2=Mem pak, 5=Rumble pak

plugin = 2

# If True, then mouse buttons may be used with this controller

mouse = False

# Scaling factor for mouse movements. For X, Y axes.

MouseSensitivity = "2.00,2.00"

# The minimum absolute value of the SDL analog joystick axis to move the 
N64 controller axis value from 0. For X, Y axes.

AnalogDeadzone = "4096,4096"

# An absolute value of the SDL joystick axis >= AnalogPeak will saturate 
the N64 controller axis value (at 80). For X, Y axes. For each axis, 
this must be greater than the corresponding AnalogDeadzone value

AnalogPeak = "32768,32768"

# Digital button configuration mappings

DPad R = "axis(4+)"

DPad L = "axis(4-)"

DPad D = "axis(5+)"

DPad U = "axis(5-)"

Start = "button(9)"

Z Trig = "button(6)"

B Button = "button(0)"

A Button = "button(1)"

C Button R = "axis(2-)"

C Button L = "axis(2+)"

C Button D = "axis(3+)"

C Button U = "axis(3-)"

R Trig = "button(7)"

L Trig = "button(4)"

Mempak switch = "button(13)"

Rumblepak switch = "button(12)"

# Analog axis configuration mappings

X Axis = "axis(0-,0+)"

Y Axis = "axis(1-,1+)"

--------------------------------------------------------------------------------------------------

*Here is the log file after running Mario Kart 64:*

/usr/games/mupen64plus --saveoptions --datadir 
/usr/share/games/mupen64plus --configdir 
/home/posiris/.config/mupen64plus --plugindir 
/usr/lib/x86_64-linux-gnu/mupen64plus --emumode 2 --osd --fullscreen 
--resolution 640x480 --gfx mupen64plus-video-glide64mk2 --audio 
mupen64plus-audio-sdl --input mupen64plus-input-sdl --rsp 
mupen64plus-rsp-hle "/home/posiris/Games/N64/Mario Kart 64.n64" __ __ __ 
_ _ ____ _ | \/ |_ _ _ __ ___ _ __ / /_ | || | | _ \| |_ _ ___ | |\/| | 
| | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| | | | | |_| | |_) 
| __/ | | | (_) |__ _| __/| | |_| \__ \ |_| |_|\__,_| .__/ \___|_| 
|_|\___/ |_| |_| |_|\__,_|___/ |_| http://code.google.com/p/mupen64plus/ 
Mupen64Plus Console User-Interface Version 2.5.0 UI-Console: attached to 
core library 'Mupen64Plus Core' version 2.5.0 UI-Console: Includes 
support for Dynamic Recompiler. UI-Console: Includes support for MIPS 
r4300 Debugger. UI-Console Warning: unrecognized command-line parameter 
'--saveoptions' Core: Goodname: Mario Kart 64 (U) [!] Core: Name: 
MARIOKART64 Core: MD5: 3A67D9986F54EB282924FCA4CD5F6DFF Core: CRC: 
3E5055B6 2E92DA52 Core: Imagetype: .v64 (byteswapped) Core: Rom size: 
12582912 bytes (or 12 Mb or 96 Megabits) Core: Version: 1446 Core: 
Manufacturer: Nintendo Core: Country: USA UI-Console Status: Cheat codes 
disabled. UI-Console: using Video plugin: 'Glide64mk2 Video Plugin' 
v2.5.0 UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' 
v2.5.0 Input Warning: missing 'plugin' parameter from config section 
AutoConfig0. Setting to 1 (none). UI-Console: using Input plugin: 
'Mupen64Plus SDL Input Plugin' v2.5.0 UI-Console: using RSP plugin: 
'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0 Video: opening 
/usr/share/games/mupen64plus/Glide64mk2.ini INI_FindSection trying to 
find name for DEFAULT Video: 3DNOW! detected. Input: 1 SDL joysticks 
were found. Input Warning: missing 'plugin' parameter from config 
section AutoConfig0. Setting to 1 (none). Input: N64 Controller #1: 
Using auto-config with SDL joystick 0 ('Pro Controller') Input: 1 
controller(s) found, 1 plugged in and usable in the emulator Input 
Warning: Couldn't open rumble support for joystick #1 Input Warning: 
Couldn't open rumble support for joystick #2 Input Warning: Couldn't 
open rumble support for joystick #3 Input Warning: Couldn't open rumble 
support for joystick #4 Input: Mupen64Plus SDL Input Plugin version 
2.5.0 initialized. Core Status: Selected state slot: 1 INI_FindSection 
trying to find name for DEFAULT INI_FindSection trying to find name for 
MARIOKART64 Video: Using TEXUMA extension. &ConfigOpenSection is 
0x7f68587faca0 (II) Setting video mode 640x480... Core: Setting video 
mode: 640x480 packed pixels extension used NPOT extension used use_fbo 1 
Video: InitCombine() Video: extensions Video: initialized. Video: Audio: 
Initializing SDL audio subsystem... Input Warning: Couldn't open rumble 
support for joystick #1 Input Warning: Couldn't open rumble support for 
joystick #2 Input Warning: Couldn't open rumble support for joystick #3 
Input Warning: Couldn't open rumble support for joystick #4 Core: 
Starting R4300 emulator: Dynamic Recompiler Core: R4300: starting 64-bit 
dynamic recompiler at: 0x7f685e0ca070 INI_FindSection trying to find 
name for UCODE Core Status: Stopping emulation. Core: R4300 emulator 
finished. Core Status: Rom closed.

**Comment by Posiris** [comment]
I just wanted to update this and say that I switch back to Elementary OS 5.1.7 and I have Mupen64Plus-QT 1.11 installed from the AppCenter (1.14 is a pain for me to try and build).  I also have Mupen64Plus 2.5.0 installed as well.  I had to pull the AutoInputCfg.ini file from GitHub to update it so I had auto Switch Pro Controller support.  I'm still unable to save in-game though as it still states that there is no mempak installed.  Here is the log file I pulled after running Mario Kart.  For some reason it's not reading that the plugin is set to 2 and is defaulting to 1.  I will add that when the controller is disconnected and I'm on keyboard, I have no such issue.  I've also tried MupenGUI out of the AppCenter and it doesn't have this issue, but the GUI needs work so I'd prefer to use yours.

/usr/games/mupen64plus --nosaveoptions --datadir /usr/share/games/mupen64plus --configdir /home/posiris/.config/mupen64plus --plugindir /usr/lib/x86_64-linux-gnu/mupen64plus --emumode 2 --osd --windowed --gfx mupen64plus-video-glide64mk2 --audio mupen64plus-audio-sdl --input mupen64plus-input-sdl --rsp mupen64plus-rsp-hle "/home/posiris/Games/N64/Mario Kart 64.n64"

 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
UI-Console:             Includes support for MIPS r4300 Debugger.
Core: Goodname: Mario Kart 64 (U) [!]
Core: Name: MARIOKART64         
Core: MD5: 3A67D9986F54EB282924FCA4CD5F6DFF
Core: CRC: 3E5055B6 2E92DA52
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1446
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Glide64mk2 Video Plugin' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
Input Warning: missing 'plugin' parameter from config section AutoConfig0. Setting to 1 (none).
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Video: opening /usr/share/games/mupen64plus/Glide64mk2.ini

INI_FindSection trying to find name for DEFAULT
Video: 3DNOW! detected.

Input: 1 SDL joysticks were found.
Input Warning: missing 'plugin' parameter from config section AutoConfig0. Setting to 1 (none).
Input: N64 Controller #1: Using auto-config with SDL joystick 0 ('Pro Controller')
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
INI_FindSection trying to find name for DEFAULT
INI_FindSection trying to find name for MARIOKART64
Video: Using TEXUMA extension.

&ConfigOpenSection is 0x7fe7ffd89f00
(II) Setting video mode 640x480...
Core: Setting video mode: 640x480
packed pixels extension used
NPOT extension used
use_fbo 1
Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Initializing SDL audio subsystem...
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7fe80ab83860
INI_FindSection trying to find name for UCODE
Core Status: Stopping emulation.
Core: R4300 emulator finished.
Core Status: Rom closed.

**Comment by Posiris** [comment]
Well I think this is partially resolved.  I updated Mupen to the latest release on GitHub and pointed QT to the directories.  I can't get the glide64mk2 plugin to work, but it doesn't work in terminal either so I don't think it's your UI.  Rice works at least, and mempak is now working.

**Comment by dh4** [comment]
Try using `mode = 0` under your controller configuration when editing it or else it will revert itself back to the automatic settings each time.

Is there an `[AutoConfig0]` section in your mupen64plus.cfg? It says the plugin parameter is missing from there. If so, set `mode = 0` there and then add `plugin = 2`

Do the instructions at https://github.com/dh4/mupen64plus-qt#building-linux not work on Elementary?

**Comment by dh4** [comment]
Have you followed the documentation at https://mupen64plus.org/wiki/index.php?title=ControllerSetup?

Looks like you should add a section titled `[Pro Controller]` to your mupen64plus.cfg.

If you get a good working config for your controller, I would send it to the email address at the bottom of that page so they can add it into their release.
