### ISSUE TITLE
Build jobs failing on Travis-CI

### ISSUE THREAD

**Issue by kishorkunal-raj** [dh4/mupen64plus-qt#55]
Hi All,
I am trying to build the package on travis-ci, but found that jobs are failing for BUILD="Windows". On Further debugging i found there might me some relative path issues. Will you please look into it and let me know how can it be fixed

logs
====
$ git clone --depth=50 --branch=master https://github.com/kishorkunal-raj/mupen64plus-qt.git kishorkunal-raj/mupen64plus-qt
0.01s
Setting environment variables from .travis.yml
$ export BUILD=windows
$ export TRAVIS_COMPILER=g++
$ export CXX=${CXX:-g++}
$ export CXX_FOR_BUILD=${CXX_FOR_BUILD:-g++}
$ export CC=${CC:-gcc}
$ export CC_FOR_BUILD=${CC_FOR_BUILD:-gcc}
$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
15.66s$ ./build-scripts/travis-ci.sh setup_qt
./build-scripts/platform/windows.sh: line 13: cd: /home/travis/build/dh4/../: No such file or directory
--2020-12-01 16:07:17--  https://www.dropbox.com/s/jr6l4lnixizqtln/travis-mxe-qt5.tar.gz
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.1, 2620:100:6018:1::a27d:301
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/jr6l4lnixizqtln/travis-mxe-qt5.tar.gz [following]
--2020-12-01 16:07:17--  https://www.dropbox.com/s/raw/jr6l4lnixizqtln/travis-mxe-qt5.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com/cd/0/inline/BEREigRgR5gh8KERdXe3EwXv5YbXvMhnU19Fg0VQzQufz33E4kh3ZbuIOhtt07JqgN9p-QQUViehCropVksE-hAS8LLUYxmayCtG4EMPcAJwK0dLXj49T24-5wTkor8wYOg/file# [following]
--2020-12-01 16:07:17--  https://uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com/cd/0/inline/BEREigRgR5gh8KERdXe3EwXv5YbXvMhnU19Fg0VQzQufz33E4kh3ZbuIOhtt07JqgN9p-QQUViehCropVksE-hAS8LLUYxmayCtG4EMPcAJwK0dLXj49T24-5wTkor8wYOg/file
Resolving uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com (uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com)... 162.125.3.15, 2620:100:6018:15::a27d:30f
Connecting to uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com (uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com)|162.125.3.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/BET0GxjRIBAoBlk4nu3KXeWKlf6WOov-TKvYrS3BpnGhI9pM676EUrSJVOAGuLg1gIoiwtacjhCyMGZP_PbDAZ3aYu4GAO7gVu-dl3kcG58mdFOg07zHTG8Aywr8aguZWw0rC3AQmDmRQkwUzyxZqkqAyAZN48KCHApWpJIaSm0kR1t3vu2k4VP-OmlnWD4fq7Mq4UTrETUjkD3BPU9aI1TXw9bnkeOWKNxvIykQ--2CIDCdUafXRtE2goT1Or1U3OQW6SXuIn0px5h7QjdgBeoRwFQbc-k_rd7u9O9JPMsoOtcFtp6uBjBZV7BcQXq0izywmQxMVQ5KP8pDJO_GBBEKCs2joWFco1NOfxV24Njt_A/file [following]
--2020-12-01 16:07:18--  https://uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com/cd/0/inline2/BET0GxjRIBAoBlk4nu3KXeWKlf6WOov-TKvYrS3BpnGhI9pM676EUrSJVOAGuLg1gIoiwtacjhCyMGZP_PbDAZ3aYu4GAO7gVu-dl3kcG58mdFOg07zHTG8Aywr8aguZWw0rC3AQmDmRQkwUzyxZqkqAyAZN48KCHApWpJIaSm0kR1t3vu2k4VP-OmlnWD4fq7Mq4UTrETUjkD3BPU9aI1TXw9bnkeOWKNxvIykQ--2CIDCdUafXRtE2goT1Or1U3OQW6SXuIn0px5h7QjdgBeoRwFQbc-k_rd7u9O9JPMsoOtcFtp6uBjBZV7BcQXq0izywmQxMVQ5KP8pDJO_GBBEKCs2joWFco1NOfxV24Njt_A/file
Reusing existing connection to uc3ee7a1a462c47bc999f240f5cb.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 301735304 (288M) [application/octet-stream]
Saving to: ‘travis-mxe-qt5.tar.gz’
travis-mxe-qt5.tar. 100%[===================>] 287.76M  71.1MB/s    in 4.0s    
2020-12-01 16:07:23 (71.1 MB/s) - ‘travis-mxe-qt5.tar.gz’ saved [301735304/301735304]
./build-scripts/platform/windows.sh: line 33: cd: /home/travis/build/dh4/mupen64plus-qt: No such file or directory
The command "./build-scripts/travis-ci.sh setup_qt" failed and exited with 1 during .
Your build has been stopped.

**Comment by dh4** [comment]
This should be fixed now. Let me know if not. I've pushed a commit to grab the GitHub username from a variable instead of it being hardcoded in the scripts.
