### ISSUE TITLE
Settings dialog: roms list emptied when new setting applied

### ISSUE THREAD

**Issue by mazes-80** [dh4/mupen64plus-qt#57]
I was hit by this bug since a while, sorry feedback comes late.
Any time I use the setting dialog the romsList is emptied.

Using QDebug.h I found that
`romList->findItems("*", Qt::MatchWildcard)
returned an empty list 
1.  one can  add as many times he whiches an already included directory.
2. editSettings empties the roms value 

I tried to replace Wildcard with RegExp matching and all is good:
`sed -i -e '/MatchWildcard/{s/Wildcard/RegExp/; s/"\*"/".*"/}' src/dialogs/settingsdialog.cpp`

Without this really tiny change all the settings dialog was unusable for me.
I noticed the wildcard were used for other things, but didn't notice the bug they involved.
Anyway the RegExp way should return the intended value.

Hope this remark to be helpful. I guess cen64-qt may be hit by this issue to.

**Comment by 3XC4L1B3R** [comment]
experienced this issue when I apt installed.
built deb from source, still experienced this issue.
applied @mazes-80 's fix and rebuilt, still experienced this issue.

one thing that works for me is directly editing mupen64plus-qt.conf, adding my rom dir, opening the settings ui, and clicking **cancel**. then the list is loaded and I can see all my roms in the ui.
opening settings and clicking the OK button still resets it to blank, but at least it works for a while...

**Comment by mazes-80** [comment]
have you tried compiling from git sources, patch already included, seems to work for an other debian user #61.

I use another distro, but it also works for 1.14 there
