### ISSUE TITLE
debugger support

### ISSUE THREAD

**Issue by eadmaster** [dh4/mupen64plus-qt#6]
followup:
http://code.google.com/p/mupen64plus/issues/detail?id=198

Please add some debugging features like breakpoints and other stuff for cheat making.

**Comment by dh4** [comment]
This isn't a full-fledged frontend, just a launcher that utilizes the console UI to do it's work. The console UI has no debugger functionality so it's not possible at this point. Perhaps if I ever decide to convert this to a proper frontend.
