### ISSUE TITLE
keyboard controls [input-sdl-control-1] resets to defaults upon loading a rom & imported roms do not show up

### ISSUE THREAD

**Issue by OP17Gaming** [dh4/mupen64plus-qt#63]
Hi there! I've recently installed the latest version of this mupen64plus-qt from the ubuntu store (snap version) on my Xubuntu 20.04 LTS install (based on debian 10), and whenever I load a Rom, the controls that i set to my liking by using the inbuilt editor, has been reset to the defaults. 

I tried multiple times including trying to edit it from mousepad in su mode because I thought the inbuilt editor didn't have the right permissions to save the config (my config location is ~/.config/mupen64plus).

Secondly, whenever I try to import my roms into mupen, the small import window appears, and when the progress bar completes, the import window closes, and nothing else happens afterwards.

If i really have to, I'll try to compile and install straight from github, but usually building and installing straight from github usually fails as there are ALWAYS errors or missing dependencies (which i can never install) when building and installing from github.

Any fixes or suggestions would be greatly appreciated!

**Comment by dh4** [comment]
Are you setting the mode correctly under the controller configuration? It should be set to zero or the controller configuration will automatically revert to the defaults mupen64plus has setup:

```
[Input-SDL-Control1]
...
# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL Device, 2=Fully automatic
mode = 0
```

For your second issue, the new release (1.15) should fix it. You can find a binary to download and run on the releases page:
https://github.com/dh4/mupen64plus-qt/releases/tag/1.15
