### ISSUE TITLE
Advice re gallerize

### ISSUE THREAD

**Issue by faygord** [dh4/mupen64plus-qt#64]
I am playing around with generalize 5.1.
I want to be able to change the delay and/or fade setting while the show is running under auto using a series of buttons in the page HTML.
In other apps written in JavaScript I do this by simply changing the value of the variable controlling the delay before image changing or the speed of the cross-fade.
I am unfamiliar with the structure of the code used in Gallerize
I understand that 'delay' and 'fade' are the variables concerned but so far have not been able to pass my changes to the executing code,
I have created a variable changeSpeed in gallery which works if called by start() but cannot be access from the html of the page.
Pointers please

**Comment by dh4** [comment]
Closing this as it's under the wrong repo. If you still need help with gallerize.js, open an issue there and I'll respond.
