### ISSUE TITLE
Make or Port this GUI to M64P

### ISSUE THREAD

**Issue by ghost** [dh4/mupen64plus-qt#65]
Hey everyone!

This isn't an issue with this project itself, however, I am trying to contact the creator of this GUI to see if there is any way to be created on the Mupen64 port "m64p" which you can find over here: @dh4 @sergiobenrocha2 @TotalCaesar659 @angeloc 

https://github.com/loganmc10/m64p

It is a much better emulator than this one with parallel GFX plugin and also RSP Parallel.

I tried replacing the files on this prject to "m64p" but at the end the console does not recognize the Parallel Plugin.

![1](https://user-images.githubusercontent.com/98130000/150449956-a656253d-8f56-4d2a-8dad-fa4d3df92a1f.jpg)

Thanks for any future answer!

**Comment by Jj0YzL5nvJ** [comment]
> I tried replacing the files on this **project** to "m64p" but at the end the console does not recognize the Parallel Plugin.

You are doing several things very, very wrong.

- You are trying to use the mupen64plus x86 (Win32) distribution to load an x64 (Win64) plugin
- `ParaLLEl RDP` only works against development versions of mupen64plus, not release versions
- **LLE RDP** plugins (`Z64`, `Angrylion`, `Angrylion-Plus`, `ParaLLEl RDP`) only work with **LLE RSP** plugins (`Z64`, `CXD4`*, `ParaLLEl RSP`)
- **MSVC** and **MSYS2** can work in a hybrid way as long as `UI-Console` and `Core` use the same subsystem

Try with **MSYS2 x64**:
[Core](https://github.com/Jj0YzL5nvJ/mupen64plus-core/releases/tag/nightly-build), [UI-Console](https://github.com/Jj0YzL5nvJ/mupen64plus-ui-console/releases/tag/nightly-build), [Audio-SDL](https://github.com/Jj0YzL5nvJ/mupen64plus-audio-sdl/releases/tag/nightly-build), [Input-SDL](https://github.com/Jj0YzL5nvJ/mupen64plus-input-sdl/releases/tag/nightly-build), [CXD4 RSP](https://github.com/Jj0YzL5nvJ/mupen64plus-rsp-cxd4/releases/tag/nightly-build), [HLE RSP](https://github.com/Jj0YzL5nvJ/mupen64plus-rsp-hle/releases/tag/nightly-build), [Z64 RSP](https://github.com/Jj0YzL5nvJ/mupen64plus-rsp-z64/releases/tag/nightly-build), [Arachnoid](https://github.com/Jj0YzL5nvJ/mupen64plus-video-arachnoid/releases/tag/nightly-build), [Glide64](https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64/releases/tag/nightly-build), [Glide64mk2](https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64mk2/releases/tag/nightly-build), [Rice](https://github.com/Jj0YzL5nvJ/mupen64plus-video-rice/releases/tag/nightly-build), [Z64 Video](https://github.com/Jj0YzL5nvJ/mupen64plus-video-z64/releases/tag/nightly-build)

**Comment by erudes91** [comment]
@Jj0YzL5nvJ Hey!
Thanks for taking the time to reply to me. I really appreciate it.
I'm not really sure what you're asking me to do. Could you please clarify?
I see several files repeated throughout all zip files.
What should I do with each one?

**Comment by Jj0YzL5nvJ** [comment]
> I'm not really sure what you're asking me to do. Could you please clarify?

It's better if you extract all the files with the nomenclature `msys-x64` in a single folder with [7-Zip](https://www.7-zip.org/).

> I see several files repeated throughout all zip files.
> What should I do with each one?

Repeated subsystem dependencies can be ignored or overwritten, I recommend you keep the most recent ones.

With that version you should be able to use `mupen64plus-video-parallel.dll` and `mupen64plus-rsp-parallel.dll`.
