### ISSUE TITLE
Doing things manually

### ISSUE THREAD

**Issue by inukaze** [dh4/mupen64plus-qt#66]
Hi there again, i am having some errors with mupen64plus

1 - Request TimeOut, well i see the time can be extended adding a line in the configuration file : 
`networktimeout=30`

2 - After i try that when i had enable the Download Info from TheGamesDb.net now show this message
"SSL handshake failed
Continue scrapping information?"

Well the unique thing is annoying me is i need click on "Yes" by each rom, just because the gui don't have an option for "My default answer is : Yes / No" for not ask by each element in romlist, and just imagine you had entire romset, and you really want scrapping each file and you should click yes, every 5 seconds, aprox during 16 hours just for complete this task.

3 - If i want to use this on an isolate pc without internet connection but i want put every cover, you can give me an example how i should make the structure of folder/files for make it work with mupen64plus under Microsoft Windows & GNU/Linux ?

Or you can add, use the second click and set manually the cover image, and the background image when the user click and empty area inside the main ui ?

4 - If possible make custom config for each game, for example if i want custom config for : 
* ----------------------------------------------------------------------
LLE Games : 
* ----------------------------------------------------------------------
* Resident Evil 2
* Indiana Jones and The Infernal Machine
* Star Wars : Rogue Squadron (3D)
* Star Wars Episode 1 : Battle For Naboo
* Shin Nihon Pro Wrestling - Toukon Road - Brave Spirit
* Shin Nihon Pro Wrestling - Toukon Road 2 - The Next Generation
* Last Legion UX
* ----------------------------------------------------------------------
* HLE Games : 
* -----------------------------------------------------------------------
* Dark Rift
* Mortal Kombat Trilogy
* Killer Instict Gold
* Perfect Dark
* GoldenEye 007
* Banjoo-Kazooie
* Banjoo-Tooie

on each specifying "rsp", "video", and differents values inside the "input" because some games i change the controller config, because i need a very diferent controller config for Star Wars Rogue Squadron, and another one for Mortal Kombat Trilogy.

well thank you very much for any help you can give me

and well if you notice someone make a internal gui for mupen64plus similar to PPSSPP-SDL under GNU/Linux, please tell me, because if prefer that internal gui, because is really awesome :D well thank you very much, see you later.

**Comment by dh4** [comment]
I'm not sure why you'd get an SSL error for thegamesdb.net. For custom setting for each ROM, you can do that already. Right click on a ROM and select "Configure Game." You can copy your mupen64plus.cfg to a different directory for each game and modify it however you like, or pass custom parameters or plugins for each game.
