### ISSUE TITLE
Translations into Brazilian Portuguese

### ISSUE THREAD

**Issue by marcelocripe** [dh4/mupen64plus-qt#69]
Hello Dan Hasting.

I can make a merge request to the file "mupen64plus-qt.desktop" and include the language translation "pt_BR" and "it" in the URL https://github.com/dh4/mupen64plus-qt/blob/master/resources/mupen64plus-qt.desktop?

I can translate the file "mupen64plus-qt_pt_BR.ts" and request it through a
"Pull requests" sending this file?

Or should I translate "cen64-qt_pt_BR.ts" and "cen64-qt.desktop"?

Please could you guide me on which project is the one you keep active and which of the two "mupen64plus-qt" or the "cen64" I can translate?

Thank you so much for developing and maintaining "mupen64plus-qt" or "cen64".

marcelocripe
(Original text in Brazilian Portuguese language)

- - - - -

Olá Dan Hasting.

Eu posso fazer um pedido de mesclagem para o arquivo "mupen64plus-qt.desktop" e incluir a tradução dos idiomas "pt_BR" e "it" no URL https://github.com/dh4/mupen64plus-qt/blob/master/resources/mupen64plus-qt.desktop?

Eu posso traduzir o arquivo "mupen64plus-qt_pt_BR.ts" e solicitar por meio de um 
"Pull requests" o envio deste arquivo?

Ou eu devo  traduzir o "cen64-qt_pt_BR.ts" e o "cen64-qt.desktop"?

Por favor, você poderia me orientar sobre qual projeto é o que você mantém ativo e qual dos dois "mupen64plus-qt" ou o "cen64" eu posso traduzir?

Muito obrigado por você desenvolver e manter o "mupen64plus-qt" o "cen64".

marcelocripe
(Texto original em idioma Português do Brasil)

**Comment by marcelocripe** [comment]
Hello Mupen64Plus-Qt developers.

I tried uploading the file "mupen64plus-qt_en_BR.ts" at URL: https://github.com/dh4/mupen64plus-qt/tree/master/resources/locale, but I got the message:

> Uploads are disabled.
>
> File uploads require push access to this repository.

I don't know how to do this kind of procedure, so I'll send the file "mupen64plus-qt_pt_BR.ts" translated to Brazilian Portuguese here.

I performed the following steps to test the "mupen64plus-qt_pt_BR.ts" file:

$ sudo apt install qttools5-dev-tools

$ lrelease mupen64plus-qt_pt_BR.ts
Updating 'mupen64plus-qt_pt_BR.qm'...
Generated 260 translation(s) (260 finished and 0 unfinished)

I managed to generate the file "mupen64plus-qt_pt_BR.qm" in antiX Linux 64bit, but I can't find out in which operating system folder I have to copy the translation file for Mupen64Plus-Qt to be able to find the translation "pt_BR" . Therefore, I couldn't check the translations in the graphical interface.

The "mupen64plus-qt_pt_BR.ts" file can also be obtained from the URL: https://github.com/marcelocripe/Mupen64Plus-Qt_pt_BR.

Thank you very much for developing and maintaining Mupen64Plus-Qt.

marcelocripe
(Original text in Brazilian Portuguese language)

[mupen64plus-qt_pt_BR.ts.zip](https://github.com/dh4/mupen64plus-qt/files/10510109/mupen64plus-qt_pt_BR.ts.zip)

- - - - -

Olá desenvolvedores do Mupen64Plus-Qt.

Eu tentei enviar o arquivo "mupen64plus-qt_pt_BR.ts" no URL: https://github.com/dh4/mupen64plus-qt/tree/master/resources/locale, mas eu recebi a mensagem:

> Os uploads estão desativados.
>
> Os uploads de arquivo requerem acesso por push a este repositório. 

Eu não sei fazer este tipo de procedimento, então eu vou enviar o arquivo "mupen64plus-qt_pt_BR.ts" traduzido para o idioma Português do Brasil aqui.

Eu realizei as seguintes etapas para testar o arquivo "mupen64plus-qt_pt_BR.ts":

$ sudo apt install qttools5-dev-tools

$ lrelease mupen64plus-qt_pt_BR.ts
Updating 'mupen64plus-qt_pt_BR.qm'...
Generated 260 translation(s) (260 finished and 0 unfinished)

Eu consegui gerar o arquivo "mupen64plus-qt_pt_BR.qm" no antiX Linux de 64 bits, mas eu não conseguir descobrir em qual pasta do sistema operacional eu tenho que copiar o arquivo de tradução para o Mupen64Plus-Qt poder encontrar a tradução "pt_BR". Por isso, eu não consegui conferir as traduções na interface gráfica.

O arquivo "mupen64plus-qt_pt_BR.ts" também pode ser obtido no URL: https://github.com/marcelocripe/Mupen64Plus-Qt_pt_BR.

Muito obrigado por desenvolverem e manterem o Mupen64Plus-Qt.

marcelocripe
(Texto original em idioma Português do Brasil)

**Comment by dh4** [comment]
Thanks for this! It's integrated into the language drop down the latest commit if you want to use it in the graphical interface. It will be in the next release.

Sorry for the delay merging this in. I have not had a lot of time to work on this project the last couple years.

**Comment by marcelocripe** [comment]
Hello, @dh4.

> Thanks for this! It's integrated into the language drop down the latest commit if you want to use it in the graphical interface. It will > be in the next release.

I will be very happy to see the translation working in the graphical interface. I could not find out in which folder the translation files with the ".qm" format are stored so I could test the translation before making the merge request. The most important thing is that in the next versions of Mupen64Plus-Qt one more language will be available for about 217 million Brazilians, in addition to the more than 63 million Portuguese speakers who will also be able to use the "pt_BR" translation in the operating system that was started in the "pt" language, since you allow changing the language through the drop-down menu.

> Sorry for the delay merging this in. I have not had a lot of time to work on this project the last couple years.

It doesn't matter how long it took for my merge request to be approved, what matters is that at some point Brazilians will be able to benefit from the "pt_BR" translation of Mupen64Plus-Qt.

The merge request https://github.com/dh4/mupen64plus-qt/pull/72 is the most recent. I received some error messages in the other merge requests. I apologize for having so many merge requests, I'm learning how to use GitHub, sometimes I get lost and don't know what to do. I hope you also use the translations from the most recent ".desktop" file.

Thank you very much.

marcelocripe
(Original text in Brazilian Portuguese language)

- - - - -

Olá, @dh4.

> Thanks for this! It's integrated into the language drop down the latest commit if you want to use it in the graphical interface. It will > be in the next release.

Eu vou ficar muito contente em poder ver a tradução funcionando na interface gráfica. Eu não consegui descobrir em qual pasta ficam armazenados os arquivos das traduções com o formato ".qm'" para eu testar a tradução antes de fazer o pedido de mesclagem. O mais importante é que nas próximas versões do Mupen64Plus-Qt mais um idioma estará disponível para cerca de 217 milhões de brasileiros, além dos mais de 63 milhões de falantes do idioma português que também poderão utilizar a tradução "pt_BR" no sistema operacional que foi iniciado no idioma "pt", já que você permite a troca do idioma  por meio do menu suspenso.

> Sorry for the delay merging this in. I have not had a lot of time to work on this project the last couple years.

Não importa o tempo que levou para o meu pedido de mesclagem ser aprovado, o que importa é que em algum momento os brasileiros poderão ser beneficiados com a tradução "pt_BR" do Mupen64Plus-Qt.

O pedido de mesclagem https://github.com/dh4/mupen64plus-qt/pull/72 é o mais recente. Eu recebi algumas mensagens de erro nos outros pedidos de mesclagens. Eu peço desculpas por ter muitos pedidos de mesclagens, eu estou aprendendo a manipular o GitHub, as vezes eu fico perdido e sem saber o que fazer. Eu espero que você também utilize as traduções do arquivo ".desktop" mais recente.

Muito obrigado.

marcelocripe
(Texto original em idioma Português do Brasil)
