### ISSUE TITLE
Please create gui for keyboard input settings

### ISSUE THREAD

**Issue by CHJ85** [dh4/mupen64plus-qt#73]
It is impossible to deal with these keycodes and set up the cfg file. Could you please create a gui for the input settings? I've been trying for hourse to find a keymap online that works with my layout.
What's so annoying about this config file is you can't simply type in "left", "right", "up", "down" etc. Although, those are the only keys I would not change in the default config setup. But changing other keys just doesn't work, because the keycodes that I find online are usually for the american keyboard or something random.

**Comment by dh4** [comment]
Closing this as the latest commits add a GUI for editing controller input. If you're trying to map your keyboard, the mupen64plus.cfg editor contains a key code reference for the SDL key codes. Make sure you set the "mode" to 0 for fully manual or mupen64plus will overwrite the changes you make.

**Comment by CHJ85** [comment]
Thanks.
