### ISSUE TITLE
New Tag

### ISSUE THREAD

**Issue by sergiobenrocha2** [dh4/mupen64plus-qt#9]
Hey! Could you create a new tag? 1.7.1 for example? I'm trying to send it to debian repos: http://mentors.debian.net/package/mupen64plus-qt

**Comment by dh4** [comment]
I have a few things I want to commit and then I'll bump the version to 1.8 and create a new tag/release. Look for this within the next day or so.

**Comment by dh4** [comment]
I've released 1.8 along with the tag.

Thanks for submitting this to Debian!

**Comment by sergiobenrocha2** [comment]
Thanks!
